version: '3.8'
services:
  anvil:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anvil_bsc_fork
    ports:
      - '8545:8545'

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass myredispassword
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'myredispassword', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongo', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
  mongo-data:
